// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/client/client.go
//
// Generated by this command:
//
//	mockgen -source pkg/client/client.go -destination pkg/client/mock/mock_secrets_client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	api "github.com/openbao/openbao/api/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretsClient is a mock of SecretsClient interface.
type MockSecretsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSecretsClientMockRecorder
	isgomock struct{}
}

// MockSecretsClientMockRecorder is the mock recorder for MockSecretsClient.
type MockSecretsClientMockRecorder struct {
	mock *MockSecretsClient
}

// NewMockSecretsClient creates a new mock instance.
func NewMockSecretsClient(ctrl *gomock.Controller) *MockSecretsClient {
	mock := &MockSecretsClient{ctrl: ctrl}
	mock.recorder = &MockSecretsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretsClient) EXPECT() *MockSecretsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSecretsClient) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecretsClientMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSecretsClient)(nil).Delete), ctx, path)
}

// List mocks base method.
func (m *MockSecretsClient) List(ctx context.Context, pathPrefix string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, pathPrefix)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecretsClientMockRecorder) List(ctx, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecretsClient)(nil).List), ctx, pathPrefix)
}

// Read mocks base method.
func (m *MockSecretsClient) Read(ctx context.Context, path string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, path)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockSecretsClientMockRecorder) Read(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockSecretsClient)(nil).Read), ctx, path)
}

// Write mocks base method.
func (m *MockSecretsClient) Write(ctx context.Context, path string, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, path, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockSecretsClientMockRecorder) Write(ctx, path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockSecretsClient)(nil).Write), ctx, path, data)
}

// MocklogicalAPI is a mock of logicalAPI interface.
type MocklogicalAPI struct {
	ctrl     *gomock.Controller
	recorder *MocklogicalAPIMockRecorder
	isgomock struct{}
}

// MocklogicalAPIMockRecorder is the mock recorder for MocklogicalAPI.
type MocklogicalAPIMockRecorder struct {
	mock *MocklogicalAPI
}

// NewMocklogicalAPI creates a new mock instance.
func NewMocklogicalAPI(ctrl *gomock.Controller) *MocklogicalAPI {
	mock := &MocklogicalAPI{ctrl: ctrl}
	mock.recorder = &MocklogicalAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklogicalAPI) EXPECT() *MocklogicalAPIMockRecorder {
	return m.recorder
}

// DeleteWithContext mocks base method.
func (m *MocklogicalAPI) DeleteWithContext(ctx context.Context, path string) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithContext", ctx, path)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWithContext indicates an expected call of DeleteWithContext.
func (mr *MocklogicalAPIMockRecorder) DeleteWithContext(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithContext", reflect.TypeOf((*MocklogicalAPI)(nil).DeleteWithContext), ctx, path)
}

// ListWithContext mocks base method.
func (m *MocklogicalAPI) ListWithContext(ctx context.Context, path string) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithContext", ctx, path)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithContext indicates an expected call of ListWithContext.
func (mr *MocklogicalAPIMockRecorder) ListWithContext(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithContext", reflect.TypeOf((*MocklogicalAPI)(nil).ListWithContext), ctx, path)
}

// ReadWithContext mocks base method.
func (m *MocklogicalAPI) ReadWithContext(ctx context.Context, path string) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadWithContext", ctx, path)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadWithContext indicates an expected call of ReadWithContext.
func (mr *MocklogicalAPIMockRecorder) ReadWithContext(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadWithContext", reflect.TypeOf((*MocklogicalAPI)(nil).ReadWithContext), ctx, path)
}

// WriteWithContext mocks base method.
func (m *MocklogicalAPI) WriteWithContext(ctx context.Context, path string, data map[string]any) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteWithContext", ctx, path, data)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteWithContext indicates an expected call of WriteWithContext.
func (mr *MocklogicalAPIMockRecorder) WriteWithContext(ctx, path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteWithContext", reflect.TypeOf((*MocklogicalAPI)(nil).WriteWithContext), ctx, path, data)
}
