apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-accounts
  namespace: cloudforge-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-accounts
  template:
    metadata:
      labels:
        app: cf-accounts
    spec:
      containers:
        - name: cf-accounts
          image: ghcr.io/jtomasevic/cloud-forge-2/cf-accounts
          ports:
            - containerPort: 8081
          env:
            - name: HTTP_ADDR
              value: ":8081"
            - name: SCYLLADB_HOSTS
              value: "host.k3d.internal:9042"
            - name: SCYLLADB_KEYSPACE
              value: "cloudforge"
            - name: KEYCLOAK_ADMIN_URL
              value: "http://host.k3d.internal:8084/auth"
            - name: KEYCLOAK_REALM
              value: "cloudforge"
            - name: KEYCLOAK_ADMIN_REALM
              value: "master"
            - name: KEYCLOAK_ADMIN_CLIENT_ID
              value: "admin-cli"
            - name: KEYCLOAK_ADMIN_USERNAME
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KEYCLOAK_LOGIN_CLIENT_ID
              value: "cf-console"
          readinessProbe:
            httpGet:
              path: /v1/accounts
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cf-accounts
  namespace: cloudforge-control-plane
spec:
  selector:
    app: cf-accounts
  ports:
    - port: 8081
      targetPort: 8081
