// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/credentials (interfaces: CredentialsRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/credentials_repository_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/credentials CredentialsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	credentials "github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/credentials"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialsRepository is a mock of CredentialsRepository interface.
type MockCredentialsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialsRepositoryMockRecorder is the mock recorder for MockCredentialsRepository.
type MockCredentialsRepositoryMockRecorder struct {
	mock *MockCredentialsRepository
}

// NewMockCredentialsRepository creates a new mock instance.
func NewMockCredentialsRepository(ctrl *gomock.Controller) *MockCredentialsRepository {
	mock := &MockCredentialsRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepository) EXPECT() *MockCredentialsRepositoryMockRecorder {
	return m.recorder
}

// GetByHash mocks base method.
func (m *MockCredentialsRepository) GetByHash(ctx context.Context, keyHash string) (credentials.APIKeyRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, keyHash)
	ret0, _ := ret[0].(credentials.APIKeyRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockCredentialsRepositoryMockRecorder) GetByHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockCredentialsRepository)(nil).GetByHash), ctx, keyHash)
}

// GetByID mocks base method.
func (m *MockCredentialsRepository) GetByID(ctx context.Context, id string) (credentials.APIKeyRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(credentials.APIKeyRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCredentialsRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCredentialsRepository)(nil).GetByID), ctx, id)
}

// Insert mocks base method.
func (m *MockCredentialsRepository) Insert(ctx context.Context, row credentials.APIKeyRow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockCredentialsRepositoryMockRecorder) Insert(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockCredentialsRepository)(nil).Insert), ctx, row)
}

// ListByAccount mocks base method.
func (m *MockCredentialsRepository) ListByAccount(ctx context.Context, accountID string) ([]credentials.APIKeyRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]credentials.APIKeyRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockCredentialsRepositoryMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockCredentialsRepository)(nil).ListByAccount), ctx, accountID)
}

// Revoke mocks base method.
func (m *MockCredentialsRepository) Revoke(ctx context.Context, id string, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockCredentialsRepositoryMockRecorder) Revoke(ctx, id, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockCredentialsRepository)(nil).Revoke), ctx, id, revokedAt)
}
