// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/networks (interfaces: NetworksRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/networks_repository_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/networks NetworksRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	networks "github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/networks"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworksRepository is a mock of NetworksRepository interface.
type MockNetworksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNetworksRepositoryMockRecorder
	isgomock struct{}
}

// MockNetworksRepositoryMockRecorder is the mock recorder for MockNetworksRepository.
type MockNetworksRepositoryMockRecorder struct {
	mock *MockNetworksRepository
}

// NewMockNetworksRepository creates a new mock instance.
func NewMockNetworksRepository(ctrl *gomock.Controller) *MockNetworksRepository {
	mock := &MockNetworksRepository{ctrl: ctrl}
	mock.recorder = &MockNetworksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworksRepository) EXPECT() *MockNetworksRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockNetworksRepository) GetByID(ctx context.Context, id string) (networks.NetworkRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(networks.NetworkRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNetworksRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNetworksRepository)(nil).GetByID), ctx, id)
}

// Insert mocks base method.
func (m *MockNetworksRepository) Insert(ctx context.Context, row networks.NetworkRow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockNetworksRepositoryMockRecorder) Insert(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockNetworksRepository)(nil).Insert), ctx, row)
}

// ListByTenant mocks base method.
func (m *MockNetworksRepository) ListByTenant(ctx context.Context, tenantID string) ([]networks.NetworkRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]networks.NetworkRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenant indicates an expected call of ListByTenant.
func (mr *MockNetworksRepositoryMockRecorder) ListByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenant", reflect.TypeOf((*MockNetworksRepository)(nil).ListByTenant), ctx, tenantID)
}

// UpdateStatus mocks base method.
func (m *MockNetworksRepository) UpdateStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNetworksRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNetworksRepository)(nil).UpdateStatus), ctx, id, status)
}
