// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/tenants (interfaces: TenantsRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/tenants_repository_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/tenants TenantsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tenants "github.com/jtomasevic/cloud-forge-2/services/cf-accounts/internal/repository/tenants"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantsRepository is a mock of TenantsRepository interface.
type MockTenantsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantsRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantsRepositoryMockRecorder is the mock recorder for MockTenantsRepository.
type MockTenantsRepositoryMockRecorder struct {
	mock *MockTenantsRepository
}

// NewMockTenantsRepository creates a new mock instance.
func NewMockTenantsRepository(ctrl *gomock.Controller) *MockTenantsRepository {
	mock := &MockTenantsRepository{ctrl: ctrl}
	mock.recorder = &MockTenantsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantsRepository) EXPECT() *MockTenantsRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockTenantsRepository) GetByID(ctx context.Context, id string) (tenants.TenantRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(tenants.TenantRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTenantsRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTenantsRepository)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockTenantsRepository) GetBySlug(ctx context.Context, slug string) (tenants.TenantRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(tenants.TenantRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockTenantsRepositoryMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockTenantsRepository)(nil).GetBySlug), ctx, slug)
}

// Insert mocks base method.
func (m *MockTenantsRepository) Insert(ctx context.Context, row tenants.TenantRow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockTenantsRepositoryMockRecorder) Insert(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTenantsRepository)(nil).Insert), ctx, row)
}

// ListByAccount mocks base method.
func (m *MockTenantsRepository) ListByAccount(ctx context.Context, accountID string, limit, offset int) ([]tenants.TenantRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID, limit, offset)
	ret0, _ := ret[0].([]tenants.TenantRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockTenantsRepositoryMockRecorder) ListByAccount(ctx, accountID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockTenantsRepository)(nil).ListByAccount), ctx, accountID, limit, offset)
}

// UpdateStatus mocks base method.
func (m *MockTenantsRepository) UpdateStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTenantsRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTenantsRepository)(nil).UpdateStatus), ctx, id, status)
}
