// Package cfprovisionerclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package cfprovisionerclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	InternalSecretScopes = "InternalSecret.Scopes"
)

// Defines values for CreateSubnetRequestType.
const (
	CreateSubnetRequestTypePrivate CreateSubnetRequestType = "private"
	CreateSubnetRequestTypePublic  CreateSubnetRequestType = "public"
)

// Defines values for GatewayStatusStatus.
const (
	GatewayStatusStatusActive       GatewayStatusStatus = "active"
	GatewayStatusStatusFailed       GatewayStatusStatus = "failed"
	GatewayStatusStatusProvisioning GatewayStatusStatus = "provisioning"
	GatewayStatusStatusRemoved      GatewayStatusStatus = "removed"
	GatewayStatusStatusRemoving     GatewayStatusStatus = "removing"
)

// Defines values for JobStatus.
const (
	JobStatusFailed    JobStatus = "failed"
	JobStatusPending   JobStatus = "pending"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
)

// Defines values for JobType.
const (
	DeprovisionNetwork JobType = "deprovision_network"
	ProvisionGateway   JobType = "provision_gateway"
	ProvisionNetwork   JobType = "provision_network"
	ProvisionSubnet    JobType = "provision_subnet"
	RemoveGateway      JobType = "remove_gateway"
)

// Defines values for NetworkProvisioningStatusStatus.
const (
	Active         NetworkProvisioningStatusStatus = "active"
	Deprovisioned  NetworkProvisioningStatusStatus = "deprovisioned"
	Deprovisioning NetworkProvisioningStatusStatus = "deprovisioning"
	Failed         NetworkProvisioningStatusStatus = "failed"
	Provisioning   NetworkProvisioningStatusStatus = "provisioning"
)

// Defines values for SubnetType.
const (
	SubnetTypePrivate SubnetType = "private"
	SubnetTypePublic  SubnetType = "public"
)

// CIDRAllocation defines model for CIDRAllocation.
type CIDRAllocation struct {
	AllocatedAt time.Time          `json:"allocatedAt"`
	NetworkId   openapi_types.UUID `json:"networkId"`
	PodCIDR     string             `json:"podCIDR"`
	SvcCIDR     string             `json:"svcCIDR"`
}

// CIDRAllocationList defines model for CIDRAllocationList.
type CIDRAllocationList struct {
	Items []CIDRAllocation `json:"items"`
}

// CreateSubnetRequest defines model for CreateSubnetRequest.
type CreateSubnetRequest struct {
	Cidr string                  `json:"cidr"`
	Type CreateSubnetRequestType `json:"type"`

	// Zone Optional availability zone or placement hint for the subnet.
	Zone *string `json:"zone,omitempty"`
}

// CreateSubnetRequestType defines model for CreateSubnetRequest.Type.
type CreateSubnetRequestType string

// Error Standard error response returned for all 4xx and 5xx responses.
type Error struct {
	// Code Machine-readable error code, e.g. "NOT_FOUND".
	Code string `json:"code"`

	// Message Human-readable error description.
	Message string `json:"message"`

	// RequestId Correlation ID from the X-Request-ID header, echoed back for tracing across service boundaries.
	RequestId *string `json:"requestId,omitempty"`
}

// GatewayStatus defines model for GatewayStatus.
type GatewayStatus struct {
	CreatedAt      *time.Time          `json:"createdAt,omitempty"`
	HttpRouteName  *string             `json:"httpRouteName,omitempty"`
	NetworkId      openapi_types.UUID  `json:"networkId"`
	PublicEndpoint *string             `json:"publicEndpoint"`
	Status         GatewayStatusStatus `json:"status"`
}

// GatewayStatusStatus defines model for GatewayStatus.Status.
type GatewayStatusStatus string

// Job defines model for Job.
type Job struct {
	CreatedAt    time.Time          `json:"createdAt"`
	ErrorMessage *string            `json:"errorMessage"`
	Id           openapi_types.UUID `json:"id"`
	NetworkId    openapi_types.UUID `json:"networkId"`
	Status       JobStatus          `json:"status"`
	Type         JobType            `json:"type"`
	UpdatedAt    *time.Time         `json:"updatedAt,omitempty"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// JobType defines model for Job.Type.
type JobType string

// JobList defines model for JobList.
type JobList struct {
	Items []Job `json:"items"`
}

// NetworkProvisioningStatus defines model for NetworkProvisioningStatus.
type NetworkProvisioningStatus struct {
	CreatedAt     time.Time                       `json:"createdAt"`
	FailureReason *string                         `json:"failureReason"`
	NetworkId     openapi_types.UUID              `json:"networkId"`
	PodCIDR       string                          `json:"podCIDR"`
	Status        NetworkProvisioningStatusStatus `json:"status"`
	SvcCIDR       string                          `json:"svcCIDR"`
	TenantId      openapi_types.UUID              `json:"tenantId"`
	UpdatedAt     *time.Time                      `json:"updatedAt,omitempty"`
	VclusterName  *string                         `json:"vclusterName,omitempty"`
}

// NetworkProvisioningStatusStatus defines model for NetworkProvisioningStatus.Status.
type NetworkProvisioningStatusStatus string

// ProvisionGatewayRequest defines model for ProvisionGatewayRequest.
type ProvisionGatewayRequest struct {
	// PublicDNSName The public DNS name to expose (e.g. tenant-abc.gateway.cloudforge.io).
	PublicDNSName string `json:"publicDNSName"`
	TlsEnabled    *bool  `json:"tlsEnabled,omitempty"`
}

// ProvisionNetworkRequest defines model for ProvisionNetworkRequest.
type ProvisionNetworkRequest struct {
	// PodCIDRPrefix Optional CIDR prefix to use. If omitted, auto-allocated from the platform supernet.
	PodCIDRPrefix *string `json:"podCIDRPrefix,omitempty"`
	Region        string  `json:"region"`

	// SvcCIDRPrefix Optional service CIDR prefix.
	SvcCIDRPrefix *string            `json:"svcCIDRPrefix,omitempty"`
	TenantId      openapi_types.UUID `json:"tenantId"`
}

// Subnet defines model for Subnet.
type Subnet struct {
	Cidr      string             `json:"cidr"`
	CreatedAt *time.Time         `json:"createdAt,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	NetworkId openapi_types.UUID `json:"networkId"`
	Type      SubnetType         `json:"type"`
	Zone      *string            `json:"zone,omitempty"`
}

// SubnetType defines model for Subnet.Type.
type SubnetType string

// SubnetList defines model for SubnetList.
type SubnetList struct {
	Items []Subnet `json:"items"`
}

// JobId defines model for jobId.
type JobId = openapi_types.UUID

// Limit defines model for limit.
type Limit = int

// NetworkId defines model for networkId.
type NetworkId = openapi_types.UUID

// Offset defines model for offset.
type Offset = int

// BadRequest Standard error response returned for all 4xx and 5xx responses.
type BadRequest = Error

// Conflict Standard error response returned for all 4xx and 5xx responses.
type Conflict = Error

// InternalServerError Standard error response returned for all 4xx and 5xx responses.
type InternalServerError = Error

// NotFound Standard error response returned for all 4xx and 5xx responses.
type NotFound = Error

// Unauthorized Standard error response returned for all 4xx and 5xx responses.
type Unauthorized = Error

// ListCIDRAllocationsParams defines parameters for ListCIDRAllocations.
type ListCIDRAllocationsParams struct {
	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Zero-based offset of the first item to return (default 0).
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListNetworkJobsParams defines parameters for ListNetworkJobs.
type ListNetworkJobsParams struct {
	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Zero-based offset of the first item to return (default 0).
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ProvisionNetworkJSONRequestBody defines body for ProvisionNetwork for application/json ContentType.
type ProvisionNetworkJSONRequestBody = ProvisionNetworkRequest

// ProvisionGatewayJSONRequestBody defines body for ProvisionGateway for application/json ContentType.
type ProvisionGatewayJSONRequestBody = ProvisionGatewayRequest

// CreateSubnetJSONRequestBody defines body for CreateSubnet for application/json ContentType.
type CreateSubnetJSONRequestBody = CreateSubnetRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListCIDRAllocations request
	ListCIDRAllocations(ctx context.Context, params *ListCIDRAllocationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJob request
	GetJob(ctx context.Context, jobId JobId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProvisionNetworkWithBody request with any body
	ProvisionNetworkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ProvisionNetwork(ctx context.Context, body ProvisionNetworkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeprovisionNetwork request
	DeprovisionNetwork(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNetworkProvisioningStatus request
	GetNetworkProvisioningStatus(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RemoveGateway request
	RemoveGateway(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGatewayStatus request
	GetGatewayStatus(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProvisionGatewayWithBody request with any body
	ProvisionGatewayWithBody(ctx context.Context, networkId NetworkId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ProvisionGateway(ctx context.Context, networkId NetworkId, body ProvisionGatewayJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListNetworkJobs request
	ListNetworkJobs(ctx context.Context, networkId NetworkId, params *ListNetworkJobsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSubnets request
	ListSubnets(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSubnetWithBody request with any body
	CreateSubnetWithBody(ctx context.Context, networkId NetworkId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateSubnet(ctx context.Context, networkId NetworkId, body CreateSubnetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListCIDRAllocations(ctx context.Context, params *ListCIDRAllocationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCIDRAllocationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJob(ctx context.Context, jobId JobId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProvisionNetworkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvisionNetworkRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProvisionNetwork(ctx context.Context, body ProvisionNetworkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvisionNetworkRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeprovisionNetwork(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeprovisionNetworkRequest(c.Server, networkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNetworkProvisioningStatus(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNetworkProvisioningStatusRequest(c.Server, networkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RemoveGateway(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveGatewayRequest(c.Server, networkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGatewayStatus(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGatewayStatusRequest(c.Server, networkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProvisionGatewayWithBody(ctx context.Context, networkId NetworkId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvisionGatewayRequestWithBody(c.Server, networkId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProvisionGateway(ctx context.Context, networkId NetworkId, body ProvisionGatewayJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvisionGatewayRequest(c.Server, networkId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListNetworkJobs(ctx context.Context, networkId NetworkId, params *ListNetworkJobsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListNetworkJobsRequest(c.Server, networkId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSubnets(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSubnetsRequest(c.Server, networkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSubnetWithBody(ctx context.Context, networkId NetworkId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSubnetRequestWithBody(c.Server, networkId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSubnet(ctx context.Context, networkId NetworkId, body CreateSubnetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSubnetRequest(c.Server, networkId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListCIDRAllocationsRequest generates requests for ListCIDRAllocations
func NewListCIDRAllocationsRequest(server string, params *ListCIDRAllocationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/cidr/allocations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetJobRequest generates requests for GetJob
func NewGetJobRequest(server string, jobId JobId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProvisionNetworkRequest calls the generic ProvisionNetwork builder with application/json body
func NewProvisionNetworkRequest(server string, body ProvisionNetworkJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewProvisionNetworkRequestWithBody(server, "application/json", bodyReader)
}

// NewProvisionNetworkRequestWithBody generates requests for ProvisionNetwork with any type of body
func NewProvisionNetworkRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeprovisionNetworkRequest generates requests for DeprovisionNetwork
func NewDeprovisionNetworkRequest(server string, networkId NetworkId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "networkId", runtime.ParamLocationPath, networkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNetworkProvisioningStatusRequest generates requests for GetNetworkProvisioningStatus
func NewGetNetworkProvisioningStatusRequest(server string, networkId NetworkId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "networkId", runtime.ParamLocationPath, networkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRemoveGatewayRequest generates requests for RemoveGateway
func NewRemoveGatewayRequest(server string, networkId NetworkId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "networkId", runtime.ParamLocationPath, networkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks/%s/gateway", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGatewayStatusRequest generates requests for GetGatewayStatus
func NewGetGatewayStatusRequest(server string, networkId NetworkId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "networkId", runtime.ParamLocationPath, networkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks/%s/gateway", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProvisionGatewayRequest calls the generic ProvisionGateway builder with application/json body
func NewProvisionGatewayRequest(server string, networkId NetworkId, body ProvisionGatewayJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewProvisionGatewayRequestWithBody(server, networkId, "application/json", bodyReader)
}

// NewProvisionGatewayRequestWithBody generates requests for ProvisionGateway with any type of body
func NewProvisionGatewayRequestWithBody(server string, networkId NetworkId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "networkId", runtime.ParamLocationPath, networkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks/%s/gateway", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListNetworkJobsRequest generates requests for ListNetworkJobs
func NewListNetworkJobsRequest(server string, networkId NetworkId, params *ListNetworkJobsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "networkId", runtime.ParamLocationPath, networkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks/%s/jobs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSubnetsRequest generates requests for ListSubnets
func NewListSubnetsRequest(server string, networkId NetworkId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "networkId", runtime.ParamLocationPath, networkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks/%s/subnets", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateSubnetRequest calls the generic CreateSubnet builder with application/json body
func NewCreateSubnetRequest(server string, networkId NetworkId, body CreateSubnetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSubnetRequestWithBody(server, networkId, "application/json", bodyReader)
}

// NewCreateSubnetRequestWithBody generates requests for CreateSubnet with any type of body
func NewCreateSubnetRequestWithBody(server string, networkId NetworkId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "networkId", runtime.ParamLocationPath, networkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/networks/%s/subnets", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListCIDRAllocationsWithResponse request
	ListCIDRAllocationsWithResponse(ctx context.Context, params *ListCIDRAllocationsParams, reqEditors ...RequestEditorFn) (*ListCIDRAllocationsResponse, error)

	// GetJobWithResponse request
	GetJobWithResponse(ctx context.Context, jobId JobId, reqEditors ...RequestEditorFn) (*GetJobResponse, error)

	// ProvisionNetworkWithBodyWithResponse request with any body
	ProvisionNetworkWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProvisionNetworkResponse, error)

	ProvisionNetworkWithResponse(ctx context.Context, body ProvisionNetworkJSONRequestBody, reqEditors ...RequestEditorFn) (*ProvisionNetworkResponse, error)

	// DeprovisionNetworkWithResponse request
	DeprovisionNetworkWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*DeprovisionNetworkResponse, error)

	// GetNetworkProvisioningStatusWithResponse request
	GetNetworkProvisioningStatusWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*GetNetworkProvisioningStatusResponse, error)

	// RemoveGatewayWithResponse request
	RemoveGatewayWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*RemoveGatewayResponse, error)

	// GetGatewayStatusWithResponse request
	GetGatewayStatusWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*GetGatewayStatusResponse, error)

	// ProvisionGatewayWithBodyWithResponse request with any body
	ProvisionGatewayWithBodyWithResponse(ctx context.Context, networkId NetworkId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProvisionGatewayResponse, error)

	ProvisionGatewayWithResponse(ctx context.Context, networkId NetworkId, body ProvisionGatewayJSONRequestBody, reqEditors ...RequestEditorFn) (*ProvisionGatewayResponse, error)

	// ListNetworkJobsWithResponse request
	ListNetworkJobsWithResponse(ctx context.Context, networkId NetworkId, params *ListNetworkJobsParams, reqEditors ...RequestEditorFn) (*ListNetworkJobsResponse, error)

	// ListSubnetsWithResponse request
	ListSubnetsWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*ListSubnetsResponse, error)

	// CreateSubnetWithBodyWithResponse request with any body
	CreateSubnetWithBodyWithResponse(ctx context.Context, networkId NetworkId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSubnetResponse, error)

	CreateSubnetWithResponse(ctx context.Context, networkId NetworkId, body CreateSubnetJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSubnetResponse, error)
}

type ListCIDRAllocationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CIDRAllocationList
	JSON401      *Unauthorized
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ListCIDRAllocationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCIDRAllocationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Job
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProvisionNetworkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Job
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ProvisionNetworkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProvisionNetworkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeprovisionNetworkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Job
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r DeprovisionNetworkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeprovisionNetworkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetNetworkProvisioningStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NetworkProvisioningStatus
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetNetworkProvisioningStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNetworkProvisioningStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RemoveGatewayResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r RemoveGatewayResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveGatewayResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGatewayStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GatewayStatus
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetGatewayStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGatewayStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProvisionGatewayResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *GatewayStatus
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ProvisionGatewayResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProvisionGatewayResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListNetworkJobsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobList
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ListNetworkJobsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListNetworkJobsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSubnetsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SubnetList
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ListSubnetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSubnetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateSubnetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Subnet
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r CreateSubnetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSubnetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListCIDRAllocationsWithResponse request returning *ListCIDRAllocationsResponse
func (c *ClientWithResponses) ListCIDRAllocationsWithResponse(ctx context.Context, params *ListCIDRAllocationsParams, reqEditors ...RequestEditorFn) (*ListCIDRAllocationsResponse, error) {
	rsp, err := c.ListCIDRAllocations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCIDRAllocationsResponse(rsp)
}

// GetJobWithResponse request returning *GetJobResponse
func (c *ClientWithResponses) GetJobWithResponse(ctx context.Context, jobId JobId, reqEditors ...RequestEditorFn) (*GetJobResponse, error) {
	rsp, err := c.GetJob(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobResponse(rsp)
}

// ProvisionNetworkWithBodyWithResponse request with arbitrary body returning *ProvisionNetworkResponse
func (c *ClientWithResponses) ProvisionNetworkWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProvisionNetworkResponse, error) {
	rsp, err := c.ProvisionNetworkWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvisionNetworkResponse(rsp)
}

func (c *ClientWithResponses) ProvisionNetworkWithResponse(ctx context.Context, body ProvisionNetworkJSONRequestBody, reqEditors ...RequestEditorFn) (*ProvisionNetworkResponse, error) {
	rsp, err := c.ProvisionNetwork(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvisionNetworkResponse(rsp)
}

// DeprovisionNetworkWithResponse request returning *DeprovisionNetworkResponse
func (c *ClientWithResponses) DeprovisionNetworkWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*DeprovisionNetworkResponse, error) {
	rsp, err := c.DeprovisionNetwork(ctx, networkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeprovisionNetworkResponse(rsp)
}

// GetNetworkProvisioningStatusWithResponse request returning *GetNetworkProvisioningStatusResponse
func (c *ClientWithResponses) GetNetworkProvisioningStatusWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*GetNetworkProvisioningStatusResponse, error) {
	rsp, err := c.GetNetworkProvisioningStatus(ctx, networkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNetworkProvisioningStatusResponse(rsp)
}

// RemoveGatewayWithResponse request returning *RemoveGatewayResponse
func (c *ClientWithResponses) RemoveGatewayWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*RemoveGatewayResponse, error) {
	rsp, err := c.RemoveGateway(ctx, networkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveGatewayResponse(rsp)
}

// GetGatewayStatusWithResponse request returning *GetGatewayStatusResponse
func (c *ClientWithResponses) GetGatewayStatusWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*GetGatewayStatusResponse, error) {
	rsp, err := c.GetGatewayStatus(ctx, networkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGatewayStatusResponse(rsp)
}

// ProvisionGatewayWithBodyWithResponse request with arbitrary body returning *ProvisionGatewayResponse
func (c *ClientWithResponses) ProvisionGatewayWithBodyWithResponse(ctx context.Context, networkId NetworkId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProvisionGatewayResponse, error) {
	rsp, err := c.ProvisionGatewayWithBody(ctx, networkId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvisionGatewayResponse(rsp)
}

func (c *ClientWithResponses) ProvisionGatewayWithResponse(ctx context.Context, networkId NetworkId, body ProvisionGatewayJSONRequestBody, reqEditors ...RequestEditorFn) (*ProvisionGatewayResponse, error) {
	rsp, err := c.ProvisionGateway(ctx, networkId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvisionGatewayResponse(rsp)
}

// ListNetworkJobsWithResponse request returning *ListNetworkJobsResponse
func (c *ClientWithResponses) ListNetworkJobsWithResponse(ctx context.Context, networkId NetworkId, params *ListNetworkJobsParams, reqEditors ...RequestEditorFn) (*ListNetworkJobsResponse, error) {
	rsp, err := c.ListNetworkJobs(ctx, networkId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListNetworkJobsResponse(rsp)
}

// ListSubnetsWithResponse request returning *ListSubnetsResponse
func (c *ClientWithResponses) ListSubnetsWithResponse(ctx context.Context, networkId NetworkId, reqEditors ...RequestEditorFn) (*ListSubnetsResponse, error) {
	rsp, err := c.ListSubnets(ctx, networkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSubnetsResponse(rsp)
}

// CreateSubnetWithBodyWithResponse request with arbitrary body returning *CreateSubnetResponse
func (c *ClientWithResponses) CreateSubnetWithBodyWithResponse(ctx context.Context, networkId NetworkId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSubnetResponse, error) {
	rsp, err := c.CreateSubnetWithBody(ctx, networkId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSubnetResponse(rsp)
}

func (c *ClientWithResponses) CreateSubnetWithResponse(ctx context.Context, networkId NetworkId, body CreateSubnetJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSubnetResponse, error) {
	rsp, err := c.CreateSubnet(ctx, networkId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSubnetResponse(rsp)
}

// ParseListCIDRAllocationsResponse parses an HTTP response from a ListCIDRAllocationsWithResponse call
func ParseListCIDRAllocationsResponse(rsp *http.Response) (*ListCIDRAllocationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCIDRAllocationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CIDRAllocationList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetJobResponse parses an HTTP response from a GetJobWithResponse call
func ParseGetJobResponse(rsp *http.Response) (*GetJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseProvisionNetworkResponse parses an HTTP response from a ProvisionNetworkWithResponse call
func ParseProvisionNetworkResponse(rsp *http.Response) (*ProvisionNetworkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProvisionNetworkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeprovisionNetworkResponse parses an HTTP response from a DeprovisionNetworkWithResponse call
func ParseDeprovisionNetworkResponse(rsp *http.Response) (*DeprovisionNetworkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeprovisionNetworkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetNetworkProvisioningStatusResponse parses an HTTP response from a GetNetworkProvisioningStatusWithResponse call
func ParseGetNetworkProvisioningStatusResponse(rsp *http.Response) (*GetNetworkProvisioningStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNetworkProvisioningStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NetworkProvisioningStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRemoveGatewayResponse parses an HTTP response from a RemoveGatewayWithResponse call
func ParseRemoveGatewayResponse(rsp *http.Response) (*RemoveGatewayResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveGatewayResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetGatewayStatusResponse parses an HTTP response from a GetGatewayStatusWithResponse call
func ParseGetGatewayStatusResponse(rsp *http.Response) (*GetGatewayStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGatewayStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GatewayStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseProvisionGatewayResponse parses an HTTP response from a ProvisionGatewayWithResponse call
func ParseProvisionGatewayResponse(rsp *http.Response) (*ProvisionGatewayResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProvisionGatewayResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest GatewayStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListNetworkJobsResponse parses an HTTP response from a ListNetworkJobsWithResponse call
func ParseListNetworkJobsResponse(rsp *http.Response) (*ListNetworkJobsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListNetworkJobsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListSubnetsResponse parses an HTTP response from a ListSubnetsWithResponse call
func ParseListSubnetsResponse(rsp *http.Response) (*ListSubnetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSubnetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SubnetList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateSubnetResponse parses an HTTP response from a CreateSubnetWithResponse call
func ParseCreateSubnetResponse(rsp *http.Response) (*CreateSubnetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateSubnetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Subnet
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
