// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/cidr (interfaces: CIDRRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/cidr_repository_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/cidr CIDRRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cidr "github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/cidr"
	gomock "go.uber.org/mock/gomock"
)

// MockCIDRRepository is a mock of CIDRRepository interface.
type MockCIDRRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCIDRRepositoryMockRecorder
	isgomock struct{}
}

// MockCIDRRepositoryMockRecorder is the mock recorder for MockCIDRRepository.
type MockCIDRRepositoryMockRecorder struct {
	mock *MockCIDRRepository
}

// NewMockCIDRRepository creates a new mock instance.
func NewMockCIDRRepository(ctrl *gomock.Controller) *MockCIDRRepository {
	mock := &MockCIDRRepository{ctrl: ctrl}
	mock.recorder = &MockCIDRRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCIDRRepository) EXPECT() *MockCIDRRepositoryMockRecorder {
	return m.recorder
}

// Allocate mocks base method.
func (m *MockCIDRRepository) Allocate(ctx context.Context, params cidr.AllocateParams) (cidr.CIDRAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allocate", ctx, params)
	ret0, _ := ret[0].(cidr.CIDRAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allocate indicates an expected call of Allocate.
func (mr *MockCIDRRepositoryMockRecorder) Allocate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allocate", reflect.TypeOf((*MockCIDRRepository)(nil).Allocate), ctx, params)
}

// Get mocks base method.
func (m *MockCIDRRepository) Get(ctx context.Context, networkID string) (cidr.CIDRAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, networkID)
	ret0, _ := ret[0].(cidr.CIDRAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCIDRRepositoryMockRecorder) Get(ctx, networkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCIDRRepository)(nil).Get), ctx, networkID)
}

// ListAll mocks base method.
func (m *MockCIDRRepository) ListAll(ctx context.Context) ([]cidr.CIDRAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]cidr.CIDRAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockCIDRRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockCIDRRepository)(nil).ListAll), ctx)
}

// Release mocks base method.
func (m *MockCIDRRepository) Release(ctx context.Context, networkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, networkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockCIDRRepositoryMockRecorder) Release(ctx, networkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockCIDRRepository)(nil).Release), ctx, networkID)
}
