// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/cilium (interfaces: CiliumClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/cilium_client_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/cilium CiliumClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cilium "github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/cilium"
	gomock "go.uber.org/mock/gomock"
)

// MockCiliumClient is a mock of CiliumClient interface.
type MockCiliumClient struct {
	ctrl     *gomock.Controller
	recorder *MockCiliumClientMockRecorder
	isgomock struct{}
}

// MockCiliumClientMockRecorder is the mock recorder for MockCiliumClient.
type MockCiliumClientMockRecorder struct {
	mock *MockCiliumClient
}

// NewMockCiliumClient creates a new mock instance.
func NewMockCiliumClient(ctrl *gomock.Controller) *MockCiliumClient {
	mock := &MockCiliumClient{ctrl: ctrl}
	mock.recorder = &MockCiliumClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCiliumClient) EXPECT() *MockCiliumClientMockRecorder {
	return m.recorder
}

// ApplyDefaultDenyPolicy mocks base method.
func (m *MockCiliumClient) ApplyDefaultDenyPolicy(ctx context.Context, vclusterNamespace, networkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDefaultDenyPolicy", ctx, vclusterNamespace, networkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyDefaultDenyPolicy indicates an expected call of ApplyDefaultDenyPolicy.
func (mr *MockCiliumClientMockRecorder) ApplyDefaultDenyPolicy(ctx, vclusterNamespace, networkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDefaultDenyPolicy", reflect.TypeOf((*MockCiliumClient)(nil).ApplyDefaultDenyPolicy), ctx, vclusterNamespace, networkID)
}

// ApplyIngressPolicy mocks base method.
func (m *MockCiliumClient) ApplyIngressPolicy(ctx context.Context, params cilium.IngressPolicyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyIngressPolicy", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyIngressPolicy indicates an expected call of ApplyIngressPolicy.
func (mr *MockCiliumClientMockRecorder) ApplyIngressPolicy(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyIngressPolicy", reflect.TypeOf((*MockCiliumClient)(nil).ApplyIngressPolicy), ctx, params)
}

// GetPolicy mocks base method.
func (m *MockCiliumClient) GetPolicy(ctx context.Context, namespace, policyName string) (cilium.PolicyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, namespace, policyName)
	ret0, _ := ret[0].(cilium.PolicyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockCiliumClientMockRecorder) GetPolicy(ctx, namespace, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockCiliumClient)(nil).GetPolicy), ctx, namespace, policyName)
}

// RemovePolicy mocks base method.
func (m *MockCiliumClient) RemovePolicy(ctx context.Context, namespace, policyName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePolicy", ctx, namespace, policyName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePolicy indicates an expected call of RemovePolicy.
func (mr *MockCiliumClientMockRecorder) RemovePolicy(ctx, namespace, policyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePolicy", reflect.TypeOf((*MockCiliumClient)(nil).RemovePolicy), ctx, namespace, policyName)
}
