// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/gateway (interfaces: GatewayClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/gateway_client_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/gateway GatewayClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gateway "github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockGatewayClient is a mock of GatewayClient interface.
type MockGatewayClient struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayClientMockRecorder
	isgomock struct{}
}

// MockGatewayClientMockRecorder is the mock recorder for MockGatewayClient.
type MockGatewayClientMockRecorder struct {
	mock *MockGatewayClient
}

// NewMockGatewayClient creates a new mock instance.
func NewMockGatewayClient(ctrl *gomock.Controller) *MockGatewayClient {
	mock := &MockGatewayClient{ctrl: ctrl}
	mock.recorder = &MockGatewayClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayClient) EXPECT() *MockGatewayClientMockRecorder {
	return m.recorder
}

// CreateAppServiceHTTPRoute mocks base method.
func (m *MockGatewayClient) CreateAppServiceHTTPRoute(ctx context.Context, params gateway.AppServiceHTTPRouteParams) (gateway.HTTPRouteInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppServiceHTTPRoute", ctx, params)
	ret0, _ := ret[0].(gateway.HTTPRouteInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppServiceHTTPRoute indicates an expected call of CreateAppServiceHTTPRoute.
func (mr *MockGatewayClientMockRecorder) CreateAppServiceHTTPRoute(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppServiceHTTPRoute", reflect.TypeOf((*MockGatewayClient)(nil).CreateAppServiceHTTPRoute), ctx, params)
}

// CreateHTTPRoute mocks base method.
func (m *MockGatewayClient) CreateHTTPRoute(ctx context.Context, params gateway.HTTPRouteParams) (gateway.HTTPRouteInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHTTPRoute", ctx, params)
	ret0, _ := ret[0].(gateway.HTTPRouteInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHTTPRoute indicates an expected call of CreateHTTPRoute.
func (mr *MockGatewayClientMockRecorder) CreateHTTPRoute(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHTTPRoute", reflect.TypeOf((*MockGatewayClient)(nil).CreateHTTPRoute), ctx, params)
}

// DeleteAppServiceHTTPRoute mocks base method.
func (m *MockGatewayClient) DeleteAppServiceHTTPRoute(ctx context.Context, namespace, appServiceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAppServiceHTTPRoute", ctx, namespace, appServiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAppServiceHTTPRoute indicates an expected call of DeleteAppServiceHTTPRoute.
func (mr *MockGatewayClientMockRecorder) DeleteAppServiceHTTPRoute(ctx, namespace, appServiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAppServiceHTTPRoute", reflect.TypeOf((*MockGatewayClient)(nil).DeleteAppServiceHTTPRoute), ctx, namespace, appServiceID)
}

// DeleteHTTPRoute mocks base method.
func (m *MockGatewayClient) DeleteHTTPRoute(ctx context.Context, namespace, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHTTPRoute", ctx, namespace, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHTTPRoute indicates an expected call of DeleteHTTPRoute.
func (mr *MockGatewayClientMockRecorder) DeleteHTTPRoute(ctx, namespace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHTTPRoute", reflect.TypeOf((*MockGatewayClient)(nil).DeleteHTTPRoute), ctx, namespace, name)
}

// GetHTTPRoute mocks base method.
func (m *MockGatewayClient) GetHTTPRoute(ctx context.Context, namespace, name string) (gateway.HTTPRouteInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHTTPRoute", ctx, namespace, name)
	ret0, _ := ret[0].(gateway.HTTPRouteInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHTTPRoute indicates an expected call of GetHTTPRoute.
func (mr *MockGatewayClientMockRecorder) GetHTTPRoute(ctx, namespace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHTTPRoute", reflect.TypeOf((*MockGatewayClient)(nil).GetHTTPRoute), ctx, namespace, name)
}
