// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/jobs (interfaces: JobsRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/jobs_repository_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/jobs JobsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jobs "github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/jobs"
	gomock "go.uber.org/mock/gomock"
)

// MockJobsRepository is a mock of JobsRepository interface.
type MockJobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobsRepositoryMockRecorder
	isgomock struct{}
}

// MockJobsRepositoryMockRecorder is the mock recorder for MockJobsRepository.
type MockJobsRepositoryMockRecorder struct {
	mock *MockJobsRepository
}

// NewMockJobsRepository creates a new mock instance.
func NewMockJobsRepository(ctrl *gomock.Controller) *MockJobsRepository {
	mock := &MockJobsRepository{ctrl: ctrl}
	mock.recorder = &MockJobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsRepository) EXPECT() *MockJobsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobsRepository) Create(ctx context.Context, params jobs.CreateJobParams) (jobs.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(jobs.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockJobsRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobsRepository)(nil).Create), ctx, params)
}

// Get mocks base method.
func (m *MockJobsRepository) Get(ctx context.Context, jobID string) (jobs.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, jobID)
	ret0, _ := ret[0].(jobs.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobsRepositoryMockRecorder) Get(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobsRepository)(nil).Get), ctx, jobID)
}

// ListByNetwork mocks base method.
func (m *MockJobsRepository) ListByNetwork(ctx context.Context, networkID string) ([]jobs.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByNetwork", ctx, networkID)
	ret0, _ := ret[0].([]jobs.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByNetwork indicates an expected call of ListByNetwork.
func (mr *MockJobsRepositoryMockRecorder) ListByNetwork(ctx, networkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByNetwork", reflect.TypeOf((*MockJobsRepository)(nil).ListByNetwork), ctx, networkID)
}

// UpdateStatus mocks base method.
func (m *MockJobsRepository) UpdateStatus(ctx context.Context, jobID string, status jobs.JobStatus, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, jobID, status, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockJobsRepositoryMockRecorder) UpdateStatus(ctx, jobID, status, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockJobsRepository)(nil).UpdateStatus), ctx, jobID, status, errorMsg)
}
