// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/kubeconfig (interfaces: KubeconfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/kubeconfig_repository_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/kubeconfig KubeconfigRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKubeconfigRepository is a mock of KubeconfigRepository interface.
type MockKubeconfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKubeconfigRepositoryMockRecorder
	isgomock struct{}
}

// MockKubeconfigRepositoryMockRecorder is the mock recorder for MockKubeconfigRepository.
type MockKubeconfigRepositoryMockRecorder struct {
	mock *MockKubeconfigRepository
}

// NewMockKubeconfigRepository creates a new mock instance.
func NewMockKubeconfigRepository(ctrl *gomock.Controller) *MockKubeconfigRepository {
	mock := &MockKubeconfigRepository{ctrl: ctrl}
	mock.recorder = &MockKubeconfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeconfigRepository) EXPECT() *MockKubeconfigRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockKubeconfigRepository) Load(ctx context.Context, tenantID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, tenantID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockKubeconfigRepositoryMockRecorder) Load(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockKubeconfigRepository)(nil).Load), ctx, tenantID)
}

// Revoke mocks base method.
func (m *MockKubeconfigRepository) Revoke(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockKubeconfigRepositoryMockRecorder) Revoke(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockKubeconfigRepository)(nil).Revoke), ctx, tenantID)
}

// Store mocks base method.
func (m *MockKubeconfigRepository) Store(ctx context.Context, tenantID string, kubeconfigBytes []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, tenantID, kubeconfigBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockKubeconfigRepositoryMockRecorder) Store(ctx, tenantID, kubeconfigBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockKubeconfigRepository)(nil).Store), ctx, tenantID, kubeconfigBytes)
}
