// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/subnets (interfaces: SubnetsRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/subnets_repository_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/subnets SubnetsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	subnets "github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/subnets"
	gomock "go.uber.org/mock/gomock"
)

// MockSubnetsRepository is a mock of SubnetsRepository interface.
type MockSubnetsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubnetsRepositoryMockRecorder
	isgomock struct{}
}

// MockSubnetsRepositoryMockRecorder is the mock recorder for MockSubnetsRepository.
type MockSubnetsRepositoryMockRecorder struct {
	mock *MockSubnetsRepository
}

// NewMockSubnetsRepository creates a new mock instance.
func NewMockSubnetsRepository(ctrl *gomock.Controller) *MockSubnetsRepository {
	mock := &MockSubnetsRepository{ctrl: ctrl}
	mock.recorder = &MockSubnetsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubnetsRepository) EXPECT() *MockSubnetsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubnetsRepository) Create(ctx context.Context, params subnets.CreateSubnetParams) (subnets.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(subnets.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubnetsRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubnetsRepository)(nil).Create), ctx, params)
}

// GetByID mocks base method.
func (m *MockSubnetsRepository) GetByID(ctx context.Context, networkID, subnetID string) (subnets.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, networkID, subnetID)
	ret0, _ := ret[0].(subnets.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSubnetsRepositoryMockRecorder) GetByID(ctx, networkID, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSubnetsRepository)(nil).GetByID), ctx, networkID, subnetID)
}

// ListByNetwork mocks base method.
func (m *MockSubnetsRepository) ListByNetwork(ctx context.Context, networkID string) ([]subnets.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByNetwork", ctx, networkID)
	ret0, _ := ret[0].([]subnets.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByNetwork indicates an expected call of ListByNetwork.
func (mr *MockSubnetsRepositoryMockRecorder) ListByNetwork(ctx, networkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByNetwork", reflect.TypeOf((*MockSubnetsRepository)(nil).ListByNetwork), ctx, networkID)
}
