// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/vcluster (interfaces: VClusterClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/vcluster_client_mock.go -package=mocks github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/vcluster VClusterClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vcluster "github.com/jtomasevic/cloud-forge-2/services/cf-provisioner/internal/repository/vcluster"
	gomock "go.uber.org/mock/gomock"
)

// MockVClusterClient is a mock of VClusterClient interface.
type MockVClusterClient struct {
	ctrl     *gomock.Controller
	recorder *MockVClusterClientMockRecorder
	isgomock struct{}
}

// MockVClusterClientMockRecorder is the mock recorder for MockVClusterClient.
type MockVClusterClientMockRecorder struct {
	mock *MockVClusterClient
}

// NewMockVClusterClient creates a new mock instance.
func NewMockVClusterClient(ctrl *gomock.Controller) *MockVClusterClient {
	mock := &MockVClusterClient{ctrl: ctrl}
	mock.recorder = &MockVClusterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVClusterClient) EXPECT() *MockVClusterClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVClusterClient) Create(ctx context.Context, params vcluster.CreateVClusterParams) (vcluster.VClusterInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(vcluster.VClusterInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVClusterClientMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVClusterClient)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockVClusterClient) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVClusterClientMockRecorder) Delete(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVClusterClient)(nil).Delete), ctx, name)
}

// Get mocks base method.
func (m *MockVClusterClient) Get(ctx context.Context, name string) (vcluster.VClusterInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(vcluster.VClusterInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVClusterClientMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVClusterClient)(nil).Get), ctx, name)
}

// GetKubeconfig mocks base method.
func (m *MockVClusterClient) GetKubeconfig(ctx context.Context, name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubeconfig", ctx, name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubeconfig indicates an expected call of GetKubeconfig.
func (mr *MockVClusterClientMockRecorder) GetKubeconfig(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeconfig", reflect.TypeOf((*MockVClusterClient)(nil).GetKubeconfig), ctx, name)
}
